site_name: OpenFOAM.YAML

copyright: Copyright &copy; 2022 Iydon Liang

repo_url: https://github.com/iydon/of.yaml

theme:
    name: material
    favicon: assets/image/favicon.png
    palette:
        primary: green
    features:
        # - navigation.instant  # https://github.com/ultrabug/mkdocs-static-i18n/issues/62
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top

plugins:
    - search
    - i18n:
        default_language: zh
        docs_structure: suffix
        languages:
            zh:
                name: 中文
            en:
                name: English
        nav_translations:
            zh:
                Home: 首页
                Installation: 安装
                YAML: YAML
                Configuration: 配置
                Interface: 接口
                Progress: 进展

markdown_extensions:
    # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
    - abbr
    # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    # https://squidfunk.github.io/mkdocs-material/reference/data-tables/
    - tables
    # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
    - footnotes
    # https://squidfunk.github.io/mkdocs-material/reference/formatting/
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    # https://squidfunk.github.io/mkdocs-material/reference/images/
    - attr_list
    - md_in_html
    # https://squidfunk.github.io/mkdocs-material/reference/lists/
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    # https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
    - pymdownx.magiclink
    # https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
    - pymdownx.smartsymbols

nav:
    - Home: index.md
    - Installation: tutorial/installation.md
    - YAML: tutorial/yaml.md
    - Configuration: tutorial/configuration.md
    - Interface: tutorial/interface.md
    - Progress: tutorial/progress.md
