---
openfoam: [7]
version: 0.11.0
order:
    - meta
    - foam
    - static
    - other
---
"0":
    U:
        FoamFile: &FoamFile
            version: 2.0
            format: ascii
            class: volVectorField
            object: U
        dimensions: "[0 1 -1 0 0]"
        internalField: uniform (0 0 0)
        boundaryField:
            inlet:
                type: zeroGradient
                value: uniform (0 0 0)
            outlet:
                type: zeroGradient
                value: uniform (0 0 0)
            walls:
                type: noSlip
            frontBack:
                type: noSlip
    alpha.vapour:
        FoamFile:
            class: volScalarField
            object: alpha.vapour
            <<: *FoamFile
        dimensions: "[0 0 0 0 0]"
        internalField: uniform 0
        boundaryField:
            inlet:
                type: calculated
                value: uniform 0
            outlet:
                type: calculated
                value: uniform 0
            walls:
                type: calculated
                value: uniform 0
            frontBack:
                type: calculated
                value: uniform 0
    k:
        FoamFile:
            class: volScalarField
            object: k
            <<: *FoamFile
        dimensions: "[0 2 -2 0 0]"
        internalField: uniform 10
        boundaryField:
            inlet:
                type: turbulentIntensityKineticEnergyInlet
                intensity: 0.05
                value: uniform 0.05
            outlet:
                type: zeroGradient
            walls:
                type: kqRWallFunction
                value: uniform 10
            frontBack:
                type: zeroGradient
    nut:
        FoamFile:
            class: volScalarField
            object: nut
            <<: *FoamFile
        dimensions: "[0 2 -1 0 0 0 0]"
        internalField: uniform 0
        boundaryField:
            inlet:
                type: calculated
                value: uniform 0
            outlet:
                type: calculated
                value: uniform 0
            walls:
                type: nutUSpaldingWallFunction
                value: uniform 0
            frontBack:
                type: nutUSpaldingWallFunction
                value: uniform 0
    p:
        FoamFile:
            class: volScalarField
            object: p
            <<: *FoamFile
        dimensions: "[1 -1 -2 0 0]"
        internalField: uniform 300e5
        boundaryField:
            inlet:
                type: totalPressure
                p0: uniform 300e5
            outlet:
                type: fixedValue
                value: uniform 100e5
            walls:
                type: zeroGradient
            frontBack:
                type: zeroGradient
    rho:
        FoamFile:
            class: volScalarField
            object: rho
            <<: *FoamFile
        dimensions: "[1 -3 0 0 0]"
        internalField: uniform 845
        boundaryField:
            inlet:
                type: fixedValue
                value: uniform 845
            outlet:
                type: fixedValue
                value: uniform 835
            walls:
                type: zeroGradient
            frontBack:
                type: zeroGradient
constant:
    thermodynamicProperties:
        FoamFile:
            class: dictionary
            object: thermodynamicProperties
            <<: *FoamFile
        barotropicCompressibilityModel: linear
        psiv: "[0 -2 2 0 0] 2.5e-06"
        rholSat: "[1 -3 0 0 0] 830"
        psil: "[0 -2 2 0 0] 5e-07"
        pSat: "[1 -1 -2 0 0] 4500"
        rhoMin: "[1 -3 0 0 0] 0.001"
    transportProperties:
        FoamFile:
            class: dictionary
            object: transportProperties
            <<: *FoamFile
        mul: "[1 -1 -1 0 0] 0.0065"
        muv: "[1 -1 -1 0 0] 5.953e-06"
        phases: (vapour water)
        water:
            transportModel: Newtonian
            nu: "[0 2 -1 0 0 0 0] 7.831e-06"
            rho: "[1 -3 0 0 0 0 0] 830"
        vapour:
            transportModel: Newtonian
            nu: "[0 2 -1 0 0 0 0] 4.252e-05"
            rho: "[1 -3 0 0 0 0 0] 0.14"
    turbulenceProperties:
        FoamFile:
            class: dictionary
            object: turbulenceProperties
            <<: *FoamFile
        simulationType: LES
        LES:
            LESModel: kEqn
            turbulence: on
            printCoeffs: on
            delta: smooth
            cubeRootVolCoeffs:
                deltaCoeff: 1
            PrandtlCoeffs:
                delta: cubeRootVol
                cubeRootVolCoeffs:
                    deltaCoeff: 1
                smoothCoeffs:
                    delta: cubeRootVol
                    cubeRootVolCoeffs:
                        deltaCoeff: 1
                    maxDeltaRatio: 1.1
                Cdelta: 0.158
            vanDriestCoeffs:
                delta: cubeRootVol
                cubeRootVolCoeffs:
                    deltaCoeff: 1
                smoothCoeffs:
                    delta: cubeRootVol
                    cubeRootVolCoeffs:
                        deltaCoeff: 1
                    maxDeltaRatio: 1.1
                Aplus: 26
                Cdelta: 0.158
            smoothCoeffs:
                delta: cubeRootVol
                cubeRootVolCoeffs:
                    deltaCoeff: 1
                maxDeltaRatio: 1.1
system:
    blockMeshDict:
        FoamFile:
            class: dictionary
            object: blockMeshDict
            <<: *FoamFile
        convertToMeters: 1.0e-3
        vertices:
            - ( 0.00  -2.50  -0.15)
            - ( 5.00  -2.50  -0.15)
            - ( 5.00  -0.15  -0.15)
            - ( 7.00  -0.15  -0.15)
            - ( 7.00  -2.50  -0.15)
            - (17.00  -2.50  -0.15)
            - (17.00  -0.15  -0.15)
            - (17.00   0.15  -0.15)
            - (17.00   2.50  -0.15)
            - ( 7.00   2.50  -0.15)
            - ( 7.00   0.15  -0.15)
            - ( 5.00   0.15  -0.15)
            - ( 5.00   2.50  -0.15)
            - ( 0.00   2.50  -0.15)
            - ( 0.00   0.15  -0.15)
            - ( 0.00  -0.15  -0.15)
            - ( 0.00  -2.50   0.15)
            - ( 5.00  -2.50   0.15)
            - ( 5.00  -0.15   0.15)
            - ( 7.00  -0.15   0.15)
            - ( 7.00  -2.50   0.15)
            - (17.00  -2.50   0.15)
            - (17.00  -0.15   0.15)
            - (17.00   0.15   0.15)
            - (17.00   2.50   0.15)
            - ( 7.00   2.50   0.15)
            - ( 7.00   0.15   0.15)
            - ( 5.00   0.15   0.15)
            - ( 5.00   2.50   0.15)
            - ( 0.00   2.50   0.15)
            - ( 0.00   0.15   0.15)
            - ( 0.00  -0.15   0.15)
        blocks:
            - hex ( 0  1  2 15 16 17 18 31) ( 50 24 10) simpleGrading (1 1 1)
            - hex (15  2 11 14 31 18 27 30) ( 50  3 10) simpleGrading (1 1 1)
            - hex (14 11 12 13 30 27 28 29) ( 50 24 10) simpleGrading (1 1 1)
            - hex ( 2  3 10 11 18 19 26 27) ( 20  3 10) simpleGrading (1 1 1)
            - hex ( 4  5  6  3 20 21 22 19) (100 24 10) simpleGrading (1 1 1)
            - hex ( 3  6  7 10 19 22 23 26) (100  3 10) simpleGrading (1 1 1)
            - hex (10  7  8  9 26 23 24 25) (100 24 10) simpleGrading (1 1 1)
        edges: []
        boundary:
            - inlet:
              type: patch
              faces:
                - (15  0 16 31)
                - (14 15 31 30)
                - (13 14 30 29)
            - outlet:
              type: patch
              faces:
                - ( 5  6 22 21)
                - ( 6  7 23 22)
                - ( 7  8 24 23)
            - walls:
              type: wall
              faces:
                - ( 1  0 16 17)
                - ( 2  1 17 18)
                - ( 3  2 18 19)
                - ( 4  3 19 20)
                - ( 5  4 20 21)
                - ( 9  8 24 25)
                - (10  9 25 26)
                - (11 10 26 27)
                - (12 11 27 28)
                - (13 12 28 29)
            - frontBack:
              type: wall
              faces:
                - ( 0 15  2  1)
                - (15 14 11  2)
                - (14 13 12 11)
                - ( 2 11 10  3)
                - ( 4  3  6  5)
                - ( 3 10  7  6)
                - (10  9  8  7)
                - (16 17 18 31)
                - (31 18 27 30)
                - (30 27 28 29)
                - (18 19 26 27)
                - (20 21 22 19)
                - (19 22 23 26)
                - (26 23 24 25)
    controlDict:
        FoamFile:
            class: dictionary
            object: controlDict
            <<: *FoamFile
        application: cavitatingFoam
        startFrom: latestTime
        startTime: 0
        stopAt: endTime
        endTime: 0.0001
        deltaT: 1e-08
        writeControl: adjustableRunTime
        writeInterval: 5e-06
        purgeWrite: 0
        writeFormat: binary
        writePrecision: 6
        writeCompression: off
        timeFormat: general
        runTimeModifiable: yes
        adjustTimeStep: on
        maxCo: 0.5
        maxAcousticCo: 50
        functions:
            fieldAverage1:
                type: fieldAverage
                libs: ("libfieldFunctionObjects.so")
                writeControl: writeTime
                fields:
                    - U:
                      mean: on
                      prime2Mean: off
                      base: time
                    - p:
                      mean: on
                      prime2Mean: off
                      base: time
                    - alpha.vapour:
                      mean: on
                      prime2Mean: off
                      base: time
    decomposeParDict:
        FoamFile:
            class: dictionary
            object: decomposeParDict
            <<: *FoamFile
        numberOfSubdomains: 4
        method: simple
        simpleCoeffs:
            n: (2 2 1)
            delta: 0.001
        hierarchicalCoeffs:
            n: (1 1 1)
            delta: 0.001
            order: xyz
        manualCoeffs:
            dataFile: |
                ""
        distributed: no
        roots: ( )
    fvSchemes:
        FoamFile:
            class: dictionary
            object: fvSchemes
            <<: *FoamFile
        ddtSchemes:
            default: Euler
        interpolationSchemes:
            default: linear
        divSchemes:
            default: none
            div(phi, rho): Gauss vanLeer
            div(rhoPhi, U): Gauss LUST grad(U)
            div(phi, k): Gauss LUST grad(k)
            div(((rho*nuEff)*dev2(T(grad(U))))): Gauss linear
        gradSchemes:
            default: Gauss linear
        laplacianSchemes:
            default: Gauss linear corrected
        snGradSchemes:
            default: corrected
    fvSolution:
        FoamFile:
            class: dictionary
            object: fvSolution
            <<: *FoamFile
        solvers:
            rho: &rho
                solver: smoothSolver
                smoother: symGaussSeidel
                tolerance: 1e-08
                relTol: 0.1
            rhoFinal:
                tolerance: 1e-08
                relTol: 0
                <<: *rho
            p: &p
                solver: GAMG
                tolerance: 0
                relTol: 0.1
                smoother: GaussSeidel
            pFinal:
                tolerance: 1e-08
                relTol: 0
                <<: *p
            (U|k|omega): &U
                solver: smoothSolver
                smoother: symGaussSeidel
                tolerance: 1e-08
                relTol: 0.1
            (U|k|omega)Final:
                tolerance: 1e-08
                relTol: 0
                <<: *U
        PIMPLE:
            nCorrectors: 3
            nNonOrthogonalCorrectors: 0
        relaxationFactors:
            equations:
                .*: 1
    mapFieldsDict:
        FoamFile:
            class: dictionary
            object: mapFieldsDict
            <<: *FoamFile
        patchMap: ( )
        cuttingPatches: ( )
    refineMeshDict:
        FoamFile:
            class: dictionary
            object: refineMeshDict
            <<: *FoamFile
        set: c0
        coordinateSystem: global
        globalCoeffs:
            tan1: (1 0 0)
            tan2: (0 1 0)
            tan3: (0 0 1)
        directions: ( tan1 tan2 tan3 )
        useHexTopology: yes
        geometricCut: no
        writeMesh: no
    topoSetDict.1:
        FoamFile:
            class: dictionary
            object: topoSetDict.1
            <<: *FoamFile
        actions:
            -
                name: c0
                type: cellSet
                action: new
                source: boxToCell
                sourceInfo:
                    box: (0.004 -0.001 -1) (0.012 0.001 1)
    topoSetDict.2:
        FoamFile:
            class: dictionary
            object: topoSetDict.2
            <<: *FoamFile
        actions:
            -
                name: c0
                type: cellSet
                action: new
                source: boxToCell
                sourceInfo:
                    box: (0.0045 -0.00075 -1) (0.0095 0.00075 1)
    topoSetDict.3:
        FoamFile:
            class: dictionary
            object: topoSetDict.3
            <<: *FoamFile
        actions:
            -
                name: c0
                type: cellSet
                action: new
                source: boxToCell
                sourceInfo:
                    box: (0.00475 -0.000375 -1) (0.009 0.000375 1)
---
-
    name: Allrun
    type: [embed, text]
    permission: 777
    data: |
        #!/bin/sh
        cd ${0%/*} || exit 1    # Run from this directory

        # Source tutorial run functions
        . $WM_PROJECT_DIR/bin/tools/RunFunctions

        # Set application name
        application=$(getApplication)

        refineMeshByCellSet()
        {
        while [ $# -ge 1 ]
        do
            if [ ! -e log.refineMesh.$1 ]
            then
                echo "Creating cell set for primary zone - $1"
                cp system/topoSetDict.$1 system/topoSetDict
                topoSet > log.topoSet.$1 2>&1

                echo "Refining primary zone - $1"
                refineMesh -dict system/refineMeshDict -overwrite \
                    > log.refineMesh.$1 2>&1
            fi
            shift
        done
        }

        runApplication blockMesh
        refineMeshByCellSet 1 2 3

        #echo "mapping fields from 2D throttle case"
        #runApplication mapFields ../throttle -sourceTime latestTime

        runApplication decomposePar
        runParallel $application
        runApplication reconstructPar

-
    name: Allclean
    type: [embed, text]
    permission: 777
    data: |
        #!/bin/sh
        cd ${0%/*} || exit 1    # Run from this directory

        # Source tutorial clean functions
        . $WM_PROJECT_DIR/bin/tools/CleanFunctions

        rm system/topoSetDict > /dev/null 2>&1
        cleanCase
---
pipeline:
    - blockMesh
    -
        command: topoSet -dict system/topoSetDict.1
        suffix: ".1"
    -
        command: refineMesh -overwrite
        suffix: ".1"
    -
        command: topoSet -dict system/topoSetDict.2
        suffix: ".2"
    -
        command: refineMesh -overwrite
        suffix: ".2"
    -
        command: topoSet -dict system/topoSetDict.3
        suffix: ".3"
    -
        command: refineMesh -overwrite
        suffix: ".3"
    - decomposePar
    - __app__
    - reconstructPar
